const contents = {
    "en": {
        "short-description": "Computer Science Student",
        "about": "About",
        "about-description": "Hello, my name is Oseias Romeiro Magalhães, and I am currently pursuing a degree in Computer Science at UnB (University of Brasília). I have experience in Data Analysis and Database Administration. I also have skills in Software Development, Automation, and Cloud Environment. I am dedicated and committed to contributing to the creation of innovative solutions and the adoption of best practices in computing.",
        "xp": "Experiences",
        "xp-description": "<li><b>Fiverr</b>: As a freelancer on the Fiverr platform, I offer specialized services in Software Development and Databases, with a focus on Database Design and Modeling, Web Application Development, Programming Support, and API Integration with external services. My projects aim to provide customized and efficient solutions to meet clients' needs, focusing on process optimization and improving data system performance.</li><li><b>Regional Federal Court of the 1st Region</b>: At TRF1, I worked directly with the DBA team, providing technical support to the team and actively collaborating on data management and infrastructure projects. My responsibilities included developing and versioning scripts for process automation and database administration, as well as managing and monitoring servers. I was also responsible for automating repetitive tasks and processes using tools like Ansible and Airflow, in addition to developing internal solutions to optimize workflows and continuously improve the services provided.</li>"
    },
    "pt": {
        "short-description": "Estudante de Ciências da Computação",
        "about": "Sobre",
        "about-description": "Olá, meu nome é Oseias Romeiro Magalhães e estou atualmente cursando Ciências da Computação na UnB (Universidade de Brasília). Tenho experiência com Análise de Dados e Administração de Banco de Dados. Também tenho habilidades em Desenvolvimentos de Softwares, Automação e Ambiente de Núvem. Sou dedicado e comprometido em contribuir para a criação de soluções inovadoras e a adoção das melhores práticas em computação.",
        "xp": "Experiências",
        "xp-description": "<li><b>Fiverr</b>: Como freelancer na plataforma Fiverr, ofereço serviços especializados em Desenvolvimento de Software e Banco de Dados, com ênfase em Design e Modelagem de Bancos de Dados, Desenvolvimento de Aplicações Web, Suporte em Programação e Integração de APIs com serviços externos. Meus projetos têm como objetivo fornecer soluções customizadas e eficientes para atender às necessidades dos clientes, com foco na otimização de processos e melhoria da performance de sistemas de dados.</li><li><b>Tribunal Regional Federal da 1ª Região</b>: No TRF1, atuei diretamente com a equipe de DBAs, prestando suporte técnico para a equipe e colaborando ativamente em projetos de gestão de dados e infraestrutura. Entre minhas responsabilidades estavam o desenvolvimento e versionamento de scripts para automação de processos e administração de Banco de Dados, além do gerenciamento e monitoramento de servidores. Também fui responsável pela automação de tarefas repetitivas e processos utilizando ferramentas como Ansible e Airflow, além de desenvolver soluções internas para otimização de fluxos de trabalho e melhoria contínua dos serviços prestados.</li>",
    }
}